github: ['']
patreon: ['yourpatreonusername']
open_collective: ['youropencollectiveusername']
ko_fi: ['yourkofiusername']
tidelift: ['yourtideliftusername']
community_bridge: ['yourcommunitybridgeusername']
liberapay: ['yourliberapayusername']
issuehunt: ['yourissuehuntusername']
otechie: ['yourotechieusername']
lfx_crowdfunding: ['yourlfxcrowdfundingusername']
