'Group: Frontend':
  - changed-files:
    - any-glob-to-any-file: ['*.html', '*.css', '*.js', '*.jsx', '*.ts', '*.tsx']
'Group: Backend':
  - changed-files:
    - any-glob-to-any-file: ['*.go', '*.rb', '*.py', '*.java', '*.kt', '*.php', '*.cpp']
'Group: Database':
  - changed-files:
    - any-glob-to-any-file: ['*.sql', '*.db', '*.db3', '*.sqlite', '*.sqlite3', '*.psql']
'Group: Machine Learning':
  - changed-files:
    - any-glob-to-any-file: ['*.ipynb', '*.py', '*.r', '*.jl', '*.pt', '*.onnx']

'Type: Design':
  - changed-files:
    - any-glob-to-any-file: ['*.sketch', '*.fig', '*.xd', '*.ai', '*.psd']
'Type: Document':
  - changed-files:
    - any-glob-to-any-file: ['*.md', '*.rst', '*.tex', '*.pdf']
'Type: Improvement':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']
'Type: New Feature':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']

'Problem: Bug':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']
'Problem: Security':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']

'O: Good 1st Issue':
  - changed-files:
    - any-glob-to-any-file: ['*.md', '*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']
'O: Help Wanted':
  - changed-files:
    - any-glob-to-any-file: ['*.md', '*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']

'Priority: High':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']
'Priority: Mid':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']
'Priority: Low':
  - changed-files:
    - any-glob-to-any-file: ['*.py', '*.js', '*.rb', '*.go', '*.java', '*.cpp']

'Feedback: Feature Request':
  - changed-files:
    - any-glob-to-any-file: ['*.md', '*.txt']
'Feedback: Question':
  - changed-files:
    - any-glob-to-any-file: ['*.md', '*.txt']
