import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="flex min-h-screen h-screen overflow-hidden">
      <p>Hello</p>
    </main>
  );
}
