name: Label Management

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        if: ${{ github.event.action == 'opened' }}
        with:
          configuration-path: .github/labels/labeling-branch.yaml
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labels/labeling-files.yaml
