name: Sync Labels

on:
  push:
    branches: [main, dev/main]
    paths:
      - .github/labels.json

jobs:
  sync-labels:
    permissions:
      issues: write
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn add -D @azu/github-label-setup
      - name: Run github-label-setup
        run: yarn github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.json